detectors:
  DuplicateMethodCall:
    exclude:
    - SublimeTextKit::Metadata::Base#self.create
    - SublimeTextKit::Metadata::Base#self.delete
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    exclude:
    - initialize
    - SublimeTextKit::Metadata::Base#self.create
