---
detectors:
  DuplicateMethodCall:
    exclude:
    - SublimeTextKit::Metadata::Base#self.create
    - SublimeTextKit::Metadata::Base#self.delete
    - SublimeTextKit::Session#load_session
    - SublimeTextKit::Session#rebuild_recent_workspaces
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    exclude:
    - initialize
    - SublimeTextKit::CLI#create_metadata
    - SublimeTextKit::CLI#metadata
    - SublimeTextKit::CLI#rebuild_metadata
    - SublimeTextKit::CLI#rebuild_session
    - SublimeTextKit::Metadata::Base#self.create
