language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - jruby
  - rbx-2
before_install: rm -f Gemfile.lock
script: bundle exec rspec spec
notifications:
  email: false
  webhooks:
    secure: "RReWxRLuQa3Rb64yfVPQDnt9MRP5eZeL2gAptFXyQPx0DiQOCtIA+FJ2xbdfDiY5O/NBzhCMLWOLZ+3Wd60plnQDlARsSWuJ+e7oe8BtbqT/kcDfVFWNm23wSUv/odcrj6b93/T9oqo0P78brgZiGbkfx/zq3qy6QWX3Qb2zaeM="
