language: ruby
env:
  global:
    secure: N2+55Mgkzd7X3taZGEDjhhiJ+ATQdzZvsmxFVaU2Q1raQo6KDZsL9Xi3etxRxtJwfrasJmMqGP5qTdST6DCnoBA6tlvJBWBRCFZJZTTR+AXETbag6uLnGFrhUaB1rX8jpwQ3Wp7+TjcNXql3JJ6SuAC94O6H3tFi42a29RF10LI=
rvm:
- 2.0.0
- 2.1.0
- jruby
before_install: rm -f Gemfile.lock
script: bundle exec rspec spec
notifications:
  email: false
  slack:
    secure: RS/aJYNYHzNnYI6WNX1BUy70MgEnlOLrs1yPUQnO9R0e4+lkxoDSkPqMb0Xbv/btf/Ez3kJGUt4et2j5dVaLimOzBCvoPIztIdElesp66mfdKEmc6c+wQRf+bImkqd0vQZiuI9h30nVSSvEM2GjiJjNm0Lf0inzJ48zLbNFhSrw=
